language: elixir

otp_release:
  - 17.5
  - 18.0
  - 19.2

elixir:
  - 1.1
  - 1.2
  - 1.3
  - 1.4

script:
  - mix local.hex --force
  - mix deps.get
  - mix ci_tests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0cb4f1057969bd327ed8
    on_success: change
    on_failure: always
    on_start: false
