language: erlang
elixir:
  - 1.0.3
otp_release:
  - 17.1
env:
  - MIX_ENV=test
script:
  - MIX_ENV=test mix do test
  - MIX_ENV=test mix whiteBread.run
  - MIX_ENV=test mix whiteBread.run --tags songs
