language: erlang
elixir:
  - 1.0.3
otp_release:
  - 17.1
env:
  - MIX_ENV=test
script:
  - mix local.hex --force
  - mix deps.get
  - mix dogma lib/ --rules Dogma.WhiteBread.Rules
  - mix test
  - mix whiteBread.run
  - mix whiteBread.run --tags songs

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0cb4f1057969bd327ed8
    on_success: change
    on_failure: always
    on_start: false
